services:
    symfony_doge.motc.client:
        alias: 'symfony_doge.motc.validator_aware_client'

    symfony_doge.motc.validator_aware_client:
        class: SymfonyDoge\MinistryOfTruthClient\ValidatorAwareClient
        arguments:
            - '@symfony_doge.motc.base_client'
            - '@symfony_doge.motc.request.validator'

    symfony_doge.motc.base_client:
        class: SymfonyDoge\MinistryOfTruthClient\Client
        arguments:
            - '@symfony_doge.motc.transport.http'
            - '@symfony_doge.motc.uri.builder'
            - '@symfony_doge.motc.request.serializer'
            - '@symfony_doge.motc.response.deserializer'

    symfony_doge.motc.dummy_client:
        class: SymfonyDoge\MinistryOfTruthClient\DummyClient
