services:
    symfony_doge.motc.client:
        alias: 'symfony_doge.motc.validator_aware_client'

    symfony_doge.motc.validator_aware_client:
        class: SymfonyDoge\MinistryOfTruthClient\ValidatorAwareClient
        arguments:
            - '@symfony_doge.motc.base_client'
            - '@validator'

    symfony_doge.motc.base_client:
        class: SymfonyDoge\MinistryOfTruthClient\Client
        arguments:
            - '@?'
            - '@symfony_doge.motc.uri.builder'
            - '@serializer'
            - '@serializer'
