services:
    symfony_doge.motc.credentials.storage:
        alias: 'symfony_doge.motc.credentials.storage.authorization_token_storage'

    symfony_doge.motc.credentials.storage.authorization_token_storage:
        class: SymfonyDoge\MinistryOfTruthClient\Bridge\Symfony\Credentials\Storage\AuthorizationTokenStorage
        arguments:
            - '%symfony_doge.motc.credentials.authorization_token%'
